// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocr.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OCRResponse_Status int32

const (
	OCRResponse_UNDEFINED  OCRResponse_Status = 0
	OCRResponse_PROCESSING OCRResponse_Status = 1
	OCRResponse_FAILED     OCRResponse_Status = 2
	OCRResponse_SUCCESS    OCRResponse_Status = 3
)

var OCRResponse_Status_name = map[int32]string{
	0: "UNDEFINED",
	1: "PROCESSING",
	2: "FAILED",
	3: "SUCCESS",
}

var OCRResponse_Status_value = map[string]int32{
	"UNDEFINED":  0,
	"PROCESSING": 1,
	"FAILED":     2,
	"SUCCESS":    3,
}

func (x OCRResponse_Status) String() string {
	return proto.EnumName(OCRResponse_Status_name, int32(x))
}

func (OCRResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_52282bc2e1d222c6, []int{1, 0}
}

type OCRRequest struct {
	// Path to the image.
	RawImgPath string `protobuf:"bytes,1,opt,name=raw_img_path,json=rawImgPath,proto3" json:"raw_img_path,omitempty"`
	// Whether to store results in the database.
	Store bool `protobuf:"varint,2,opt,name=store,proto3" json:"store,omitempty"`
	// Whether to return image path only after the file has been
	// parsed and stored.
	Async                bool     `protobuf:"varint,3,opt,name=async,proto3" json:"async,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OCRRequest) Reset()         { *m = OCRRequest{} }
func (m *OCRRequest) String() string { return proto.CompactTextString(m) }
func (*OCRRequest) ProtoMessage()    {}
func (*OCRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52282bc2e1d222c6, []int{0}
}

func (m *OCRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OCRRequest.Unmarshal(m, b)
}
func (m *OCRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OCRRequest.Marshal(b, m, deterministic)
}
func (m *OCRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OCRRequest.Merge(m, src)
}
func (m *OCRRequest) XXX_Size() int {
	return xxx_messageInfo_OCRRequest.Size(m)
}
func (m *OCRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OCRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OCRRequest proto.InternalMessageInfo

func (m *OCRRequest) GetRawImgPath() string {
	if m != nil {
		return m.RawImgPath
	}
	return ""
}

func (m *OCRRequest) GetStore() bool {
	if m != nil {
		return m.Store
	}
	return false
}

func (m *OCRRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

type OCRResponse struct {
	ParsedImgPath        string             `protobuf:"bytes,1,opt,name=parsed_img_path,json=parsedImgPath,proto3" json:"parsed_img_path,omitempty"`
	Status               OCRResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=protos.OCRResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OCRResponse) Reset()         { *m = OCRResponse{} }
func (m *OCRResponse) String() string { return proto.CompactTextString(m) }
func (*OCRResponse) ProtoMessage()    {}
func (*OCRResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52282bc2e1d222c6, []int{1}
}

func (m *OCRResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OCRResponse.Unmarshal(m, b)
}
func (m *OCRResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OCRResponse.Marshal(b, m, deterministic)
}
func (m *OCRResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OCRResponse.Merge(m, src)
}
func (m *OCRResponse) XXX_Size() int {
	return xxx_messageInfo_OCRResponse.Size(m)
}
func (m *OCRResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OCRResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OCRResponse proto.InternalMessageInfo

func (m *OCRResponse) GetParsedImgPath() string {
	if m != nil {
		return m.ParsedImgPath
	}
	return ""
}

func (m *OCRResponse) GetStatus() OCRResponse_Status {
	if m != nil {
		return m.Status
	}
	return OCRResponse_UNDEFINED
}

func init() {
	proto.RegisterEnum("protos.OCRResponse_Status", OCRResponse_Status_name, OCRResponse_Status_value)
	proto.RegisterType((*OCRRequest)(nil), "protos.OCRRequest")
	proto.RegisterType((*OCRResponse)(nil), "protos.OCRResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OCRServiceClient is the client API for OCRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OCRServiceClient interface {
	DoOCR(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error)
}

type oCRServiceClient struct {
	cc *grpc.ClientConn
}

func NewOCRServiceClient(cc *grpc.ClientConn) OCRServiceClient {
	return &oCRServiceClient{cc}
}

func (c *oCRServiceClient) DoOCR(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error) {
	out := new(OCRResponse)
	err := c.cc.Invoke(ctx, "/protos.OCRService/DoOCR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OCRServiceServer is the server API for OCRService service.
type OCRServiceServer interface {
	DoOCR(context.Context, *OCRRequest) (*OCRResponse, error)
}

func RegisterOCRServiceServer(s *grpc.Server, srv OCRServiceServer) {
	s.RegisterService(&_OCRService_serviceDesc, srv)
}

func _OCRService_DoOCR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OCRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCRServiceServer).DoOCR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OCRService/DoOCR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCRServiceServer).DoOCR(ctx, req.(*OCRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OCRService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.OCRService",
	HandlerType: (*OCRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoOCR",
			Handler:    _OCRService_DoOCR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocr.proto",
}

func init() { proto.RegisterFile("ocr.proto", fileDescriptor_52282bc2e1d222c6) }

var fileDescriptor_52282bc2e1d222c6 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0xb4, 0x34, 0x9f, 0x99, 0xda, 0x1a, 0x46, 0x0f, 0xa1, 0xa7, 0x90, 0x83, 0xf4,
	0x14, 0x24, 0xde, 0x45, 0x49, 0x52, 0x09, 0x48, 0x52, 0x76, 0xe9, 0xc5, 0x4b, 0x59, 0xe3, 0xd2,
	0xf6, 0xd0, 0x6e, 0xdc, 0xd9, 0x5a, 0xfc, 0x4d, 0xfe, 0x49, 0xe9, 0xae, 0x82, 0x8a, 0xa7, 0x65,
	0x9e, 0x1d, 0xe6, 0x79, 0x79, 0x21, 0x50, 0xad, 0x4e, 0x3b, 0xad, 0x8c, 0x42, 0xdf, 0x3e, 0x94,
	0x3c, 0x02, 0x34, 0x39, 0x63, 0xf2, 0x65, 0x2f, 0xc9, 0x60, 0x0c, 0xa7, 0x5a, 0x1c, 0x96, 0x9b,
	0xed, 0x6a, 0xd9, 0x09, 0xb3, 0x8e, 0xbc, 0xd8, 0x9b, 0x06, 0x0c, 0xb4, 0x38, 0x54, 0xdb, 0xd5,
	0x5c, 0x98, 0x35, 0x5e, 0xc0, 0x80, 0x8c, 0xd2, 0x32, 0xea, 0xc5, 0xde, 0xf4, 0x84, 0xb9, 0xe1,
	0x48, 0x05, 0xbd, 0xed, 0xda, 0xa8, 0xef, 0xa8, 0x1d, 0x92, 0x77, 0x0f, 0x86, 0xf6, 0x38, 0x75,
	0x6a, 0x47, 0x12, 0x2f, 0xe1, 0xac, 0x13, 0x9a, 0xe4, 0xf3, 0x6f, 0xc1, 0xc8, 0xe1, 0x2f, 0x47,
	0x06, 0x3e, 0x19, 0x61, 0xf6, 0x64, 0x25, 0xe3, 0x6c, 0xe2, 0x32, 0x53, 0xfa, 0xed, 0x58, 0xca,
	0xed, 0x06, 0xfb, 0xdc, 0x4c, 0x6e, 0xc1, 0x77, 0x04, 0x47, 0x10, 0x2c, 0xea, 0xa2, 0x9c, 0x55,
	0x75, 0x59, 0x84, 0xff, 0x70, 0x0c, 0x30, 0x67, 0x4d, 0x5e, 0x72, 0x5e, 0xd5, 0xf7, 0xa1, 0x87,
	0x00, 0xfe, 0xec, 0xae, 0x7a, 0x28, 0x8b, 0xb0, 0x87, 0x43, 0xf8, 0xcf, 0x17, 0xf9, 0xf1, 0x2f,
	0xec, 0x67, 0x37, 0xb6, 0x09, 0x2e, 0xf5, 0xeb, 0xa6, 0x95, 0x78, 0x05, 0x83, 0x42, 0x35, 0x39,
	0x43, 0xfc, 0x21, 0xb7, 0x35, 0x4d, 0xce, 0xff, 0x08, 0xf4, 0xe4, 0x1a, 0xbd, 0xfe, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x6a, 0xd0, 0xbc, 0x12, 0x65, 0x01, 0x00, 0x00,
}
